### ISSUE TITLE
Old leaves textures?

### ISSUE THREAD

**Issue by ReaLeCHL** [skywardmc/additive-installer#7]
Why do the leaves have the old texture?
![image](https://github.com/skywardmc/additive-installer/assets/165544616/e896039c-ab1d-4d21-932e-04cd44361d1a)

**Comment by ReaLeCHL** [comment]
Also, why are there mods in the resource packs screen?
![image](https://github.com/skywardmc/additive-installer/assets/165544616/6db257d2-d822-4093-a739-21f62c40b272)

**Comment by Gaming32** [comment]
These issues have nothing to do with the installer.

**Comment by ReaLeCHL** [comment]
Oh ok.
